# Generated by Django 2.2.5 on 2019-12-26 10:35

import RMEC_Employee.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMEC_Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', RMEC_Employee.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
